version: "3.8"

services:
  apache:
    build: .
    container_name: xampp_apache
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - mysql
    networks:
      - xampp_network

  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: xampp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projeto
      MYSQL_USER: aluno
      MYSQL_PASSWORD: 123456
    ports:
      - "3309:3306" # <- porta externa 3309, interna continua 3306
    volumes:
      - /mysql_data:/var/lib/mysql
    networks:
      - xampp_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: xampp_phpmyadmin
    restart: always
    ports:
      - "8091:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - xampp_network

networks:
  xampp_network:
